# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MmIyODIzZDg3NWU5ODZhYjAzZmYxODM5YWZmOWZjYWYyMGI1NjA5YjFiOGMxNmQ4ZjdjNzlmYzVjMzU2OTdkMmZhMWFiMDI4ZDc3MTRjOGU5YWQ4YzEwZGNiMTE3N2ZkNDRkZDE3ZDFlM2I4M2ZkYzBiYzA2NjAzYTIyYjc5NjY=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
